name: Magic Acid
description: "My blog. Chemistry and stuff"
markdown: redcarpet
pygments: true
url: "magicacid.com"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Chemistry and stuff."
  -
    scope:
      path: "_posts/"
    values:
      layout: post