name: Magic Acid
description: "My blog. Chemistry and stuff"
markdown: kramdown
highlighter: pygments
url: "http://localhost:8000"
debug: True
email: "mark.wolf.music@gmail.com"
excerpt_separator: "<!-- more -->"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "Chemistry and stuff."
  -
    scope:
      path: "_posts/"
    values:
      layout: post